/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TODO;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class ToDoProject {

    public static void main(String[] args) {

        ApplicationContext applicationContext = SpringApplication.run(ToDoProject.class);
    }
}
